### ISSUE TITLE
Bug when I want to select the minifig.

### ISSUE THREAD

**Issue by LoloStudios** [BlenderBricks/EpicFigRig#11]
I have Blender 3.4.1.
When I select the Minifig, I click on 'Rig selected Minifigure' button and I have a Python error message : line 348 in execute if "3814" in y.data.name: Attribute error: 'Nonetype' object has no attribute 'name'. 

![Bug_blender](https://user-images.githubusercontent.com/128326221/226210410-48191cbb-bfe0-4f14-b4c2-d9aaf43d19a8.png)

**Comment by LoloStudios** [comment]
I finally found the fork of JabLab that works on Blender 3.4.
You can find it at https://github.com/BlenderBricks/EpicFigRig/tree/jablab-releases
Thank you very much JabLab !!!
